### ISSUE TITLE
Link to "NASA Access project" in the README is broken

### ISSUE THREAD

**Issue by bilts** [cirrus-geo/cirrus#31]
The link is broken.  I'm not sure where it was supposed to go.  Also, nit: ACCESS is an acronym (Advancing Collaborative Connections for Earth System Science) and should be all caps.  This could be an appropriate link, though even better if you can point to some sort of abstract for the specific project: https://earthdata.nasa.gov/esds/competitive-programs/access

**Comment by quetcodesfire** [comment]
What is the exact name of the project?
